# Blockchain provider used by Atlas, our off-chain transaction building tool.
# Head over to https://atlas-app.io/getting-started/endpoints#providing-data-provider section to know how to configure `coreProvider` and what all options are available for it.
coreProvider:
  maestroToken: YOUR_MAESTRO_TOKEN
  turboSubmit: false
# Network id, only `mainnet` and `preprod` are supported for at the moment.
networkId: mainnet
databasePath: "txs.json"
# Logging configuration. It's an array to cater for potentially multiple scribes.
# See it's description mentioned at https://atlas-app.io/getting-started/endpoints#providing-data-provider for more information.
logging:
  - type:
      tag: stderr
      # Possible values of `severity` are `Debug`, `Info`, `Warning` and `Error`.
    severity: Debug
      # Possible values of `verbosity` are `V0`, `V1`, `V2`, `V3` and `V4`. Consult https://hackage.haskell.org/package/katip-0.8.8.0/docs/Katip.html#t:Verbosity for more information about it.
    verbosity: V2
  # Port to serve endpoints at.
port: 8082
  # API key to protect server endpoints with. It's value must be provided under `api-key` header of request.
serverApiKey: 123456
wallet:
  tag: mnemonicWallet
  contents:
    mnemonic:
      - health
      - unable
      - dog
      - lend
      - artefact
      - arctic
      - dinner
      - energy
      - silent
      - wealth
      - shock
      - safe
      - glad
      - mail
      - gas
      - flag
      - beauty
      - penalty
      - mixed
      - garbage
      - erupt
      - wonder
      - magnet
      - around
    # Account index.
    accIx: 0
    # Payment address index.
    addrIx: 0
accumulationValue: 100000000
maybeScriptRef:
  tag: nothing
maybeThreadTokenRef:
  tag: nothing