accumulationValue: 100000000
coreProvider:
  maestroToken: aCmZhlBBq7f3dHls9INwu9KlsNQwUXS3
  turboSubmit: false
databasePath: txs.json
logging:
- severity: Debug
  type:
    tag: stderr
  verbosity: V2
maybeScriptRef: da98086dd1b614be7d4f8aca19164a31594dbf2bc7ff0d25a7cdfbce8dd2faad#0
maybeThreadTokenRef: 997fa89d285b888dd2860a9cb4a53b1ec56add3908ff9337468f437549d7b1a5#7
networkId: preprod
port: 8082
serverApiKey: '123456'
wallet:
  contents:
    accIx: 0
    addrIx: 0
    mnemonic:
    - health
    - unable
    - dog
    - lend
    - artefact
    - arctic
    - dinner
    - energy
    - silent
    - wealth
    - shock
    - safe
    - glad
    - mail
    - gas
    - flag
    - beauty
    - penalty
    - mixed
    - garbage
    - erupt
    - wonder
    - magnet
    - around
  tag: mnemonicWallet
