accumulationValue: 100000000
coreProvider:
  maestroToken: aCmZhlBBq7f3dHls9INwu9KlsNQwUXS3
  turboSubmit: false
databasePath: database/txs.json
logging:
- severity: Debug
  type:
    tag: stderr
  verbosity: V2
maybeScriptRef: 676c5de12c5c536e16bf50cf7fac09d66786c00464dd994e6ae174ffb7c0c7c5#0
networkId: preprod
port: 8082
serverApiKey: '123456'
threadTokenRefs:
- ce62b5af7d204ff270c07a84f070b56857ae51f0d3742f9dd3bc7ca2591fc84f#4
- 74eab31b1c26190a2998208e8eac556601f98a4f54072f30f8da3468c04ae79a#1
wallet:
  contents:
    accIx: 0
    addrIx: 0
    mnemonic:
    - health
    - unable
    - dog
    - lend
    - artefact
    - arctic
    - dinner
    - energy
    - silent
    - wealth
    - shock
    - safe
    - glad
    - mail
    - gas
    - flag
    - beauty
    - penalty
    - mixed
    - garbage
    - erupt
    - wonder
    - magnet
    - around
  tag: mnemonicWallet
