accumulationValue:
  lovelace: 1000000000
coreProvider:
  maestroToken: aCmZhlBBq7f3dHls9INwu9KlsNQwUXS3
  turboSubmit: false
databasePath: database/transactions.json
logging:
- severity: Debug
  type:
    tag: stderr
  verbosity: V2
maybeScriptRef: c4a5b80657e6a7a140e46b17a5137bff9cc6854bb31596cd2dd7e4e5dbc97481#0
networkId: preprod
port: 8083
serverApiKey: '123456'
threadTokenRefs:
- a5d8c42437e7d1e6ebbc36411ba85724c1619f188fdb58c0f44b42ff3ac821ff#3
wallet:
  contents:
    accIx: 0
    addrIx: 0
    mnemonic:
    - health
    - unable
    - dog
    - lend
    - artefact
    - arctic
    - dinner
    - energy
    - silent
    - wealth
    - shock
    - safe
    - glad
    - mail
    - gas
    - flag
    - beauty
    - penalty
    - mixed
    - garbage
    - erupt
    - wonder
    - magnet
    - around
  tag: mnemonicWallet
