accumulationValue:
  lovelace: 1000000000
cachePath: database/cache.json
coreProvider:
  maestroToken: aCmZhlBBq7f3dHls9INwu9KlsNQwUXS3
  turboSubmit: false
databasePath: database/1000ada.json
logging:
- severity: Debug
  type:
    tag: stderr
  verbosity: V2
maybeScriptRef: eb28676b8cb1517056160e4f1c4ca681c9a7875e3642ff1d20496a4513425c04#0
networkId: preprod
port: 8083
serverApiKey: '123456'
threadTokenRefs:
- d7aceff073fe4a5888744f5551677198c439dcc8c3f844dc206c2707498ed9c8#1
- 57e6cfe499073be20261ac72c13d6d0a0ab375e43c4123c3e61264df18c36d1b#3
- c68fdc268bd75d0e4c4f61e1c94096a7eb9f17dfdb40c788078870e0542ca6bb#1
wallet:
  contents:
    accIx: 0
    addrIx: 0
    mnemonic:
    - health
    - unable
    - dog
    - lend
    - artefact
    - arctic
    - dinner
    - energy
    - silent
    - wealth
    - shock
    - safe
    - glad
    - mail
    - gas
    - flag
    - beauty
    - penalty
    - mixed
    - garbage
    - erupt
    - wonder
    - magnet
    - around
  tag: mnemonicWallet
