accumulationValue:
  lovelace: 100000000
cachePath: database/cache.json
coreProvider:
  maestroToken: aCmZhlBBq7f3dHls9INwu9KlsNQwUXS3
  turboSubmit: false
databasePath: database/100ada.json
logging:
- severity: Debug
  type:
    tag: stderr
  verbosity: V2
maybeScriptRef: 9e8b4ef05e8fde8fb0f43965497a15734a27d77e0451bf60f730f3e5b50ad08a#0
networkId: preprod
port: 8082
serverApiKey: '123456'
threadTokenRefs:
- 57e6cfe499073be20261ac72c13d6d0a0ab375e43c4123c3e61264df18c36d1b#2
- a14fee7b0692b98afb7b7756a94b29e5fe504be283ec87b5c93e1d04067f5346#3
- 7b1822a57f690726e62d824483afca4aa3fe3509c79a5cd5ce1791beaae8731d#2
- 3c82a57a5a5ddd06cf0068b627118505210de6afbced79388426cc41aa5f1065#2
wallet:
  contents:
    accIx: 0
    addrIx: 0
    mnemonic:
    - health
    - unable
    - dog
    - lend
    - artefact
    - arctic
    - dinner
    - energy
    - silent
    - wealth
    - shock
    - safe
    - glad
    - mail
    - gas
    - flag
    - beauty
    - penalty
    - mixed
    - garbage
    - erupt
    - wonder
    - magnet
    - around
  tag: mnemonicWallet
