accumulationValue:
  acf8a16a63d0203e18a1fa1050e21c0754c10ea55c5e24ae15193325.494e4459: 1000
coreProvider:
  maestroToken: aCmZhlBBq7f3dHls9INwu9KlsNQwUXS3
  turboSubmit: false
databasePath: database/transactions.json
logging:
- severity: Debug
  type:
    tag: stderr
  verbosity: V2
maybeScriptRef:
networkId: preprod
port: 8084
serverApiKey: '123456'
threadTokenRefs: []
wallet:
  contents:
    accIx: 0
    addrIx: 0
    mnemonic:
    - health
    - unable
    - dog
    - lend
    - artefact
    - arctic
    - dinner
    - energy
    - silent
    - wealth
    - shock
    - safe
    - glad
    - mail
    - gas
    - flag
    - beauty
    - penalty
    - mixed
    - garbage
    - erupt
    - wonder
    - magnet
    - around
  tag: mnemonicWallet
