name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate:
    uses: ./.github/workflows/haskell.yml
      